<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\QuestionBank;
use App\Models\Topic;
use App\Models\User;
use Faker\Generator as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class QuestionBankSeeder extends Seeder
{
    public function __construct(private Faker $faker) {}

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $organization = Organization::query()->where('slug', 'bataan-general-hospital')->first()
            ?? Organization::query()->first();

        if (! $organization) {
            $organization = Organization::create([
                'name' => 'Bataan General Hospital',
                'slug' => 'bataan-general-hospital',
                'description' => 'Autogenerated organization for question bank seeding.',
                'type' => 'institution',
                'is_active' => true,
            ]);
        }

        $creator = User::query()->first();

        if (! $creator) {
            $creator = User::factory()->create([
                'name' => 'Question Bank Seeder',
                'email' => 'question-bank-seeder@example.com',
            ]);
        }

        $topicIds = Topic::query()->pluck('id');
        $topicLookup = Topic::query()->pluck('id', 'name');

        if ($topicIds->isEmpty()) {
            $topic = Topic::create([
                'name' => 'General Pathology',
                'slug' => Str::slug('General Pathology'),
                'description' => 'Fallback topic generated by the QuestionBankSeeder.',
                'organization_id' => null,
                'is_global' => true,
            ]);

            $topicIds = collect([$topic->id]);
        }

        $blueprints = collect($this->questionBlueprints());

        if ($blueprints->count() < 50) {
            $blueprints = $blueprints->cycle()->take(50)->values();
        } else {
            $blueprints = $blueprints->take(50);
        }

        foreach ($blueprints as $blueprint) {
            $topicId = $topicLookup->get($blueprint['topic']) ?? $topicIds->random();

            $question = QuestionBank::create([
                'organization_id' => $organization->id,
                'owner_type' => 'institution', // Question bank seeder creates institution questions
                'topic_id' => $topicId,
                'created_by' => $creator->id,
                'question_type' => 'multiple_choice',
                'question_text' => $blueprint['question'],
                'points' => $blueprint['points'] ?? 1,
                'explanation' => $blueprint['explanation'],
                'difficulty_level' => $blueprint['difficulty'] ?? 'medium',
                'is_approved' => true,
                'approved_by' => $creator->id,
                'approved_at' => now(),
            ]);

            foreach ($blueprint['choices'] as $order => $choiceText) {
                $question->choices()->create([
                    'choice_text' => $choiceText,
                    'is_correct' => $order === 0,
                    'order' => $order + 1,
                ]);
            }
        }
    }

    /**
     * Realistic multiple-choice question templates.
     *
     * @return array<int, array<string, mixed>>
     */
    private function questionBlueprints(): array
    {
        return [
            [
                'topic' => 'Hematology',
                'question' => 'A 32-year-old man with progressive leukocytosis is diagnosed with chronic myeloid leukemia. Which cytogenetic abnormality confirms the diagnosis?',
                'choices' => [
                    't(9;22) BCR-ABL fusion gene (Philadelphia chromosome)',
                    't(8;14) MYC translocation involving the heavy-chain enhancer',
                    't(15;17) PML-RARA fusion characteristic of APL',
                    't(12;21) ETV6-RUNX1 rearrangement seen in ALL',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'The Philadelphia chromosome t(9;22) creating BCR-ABL is pathognomonic for chronic myeloid leukemia.',
            ],
            [
                'topic' => 'Pathology',
                'question' => 'Which necrotic pattern is classically associated with Mycobacterium tuberculosis infection in lymph nodes?',
                'choices' => [
                    'Caseous necrosis with amorphous granular debris',
                    'Liquefactive necrosis secondary to lysosomal enzymes',
                    'Fat necrosis with saponification of adipocytes',
                    'Fibrinoid necrosis of vascular walls',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Granulomatous inflammation from TB produces caseous necrosis with cheese-like gross appearance.',
            ],
            [
                'topic' => 'Histology',
                'question' => 'Type I pneumocytes primarily serve which function within the alveolus?',
                'choices' => [
                    'Form the simple squamous barrier for gas exchange',
                    'Produce surfactant rich in dipalmitoylphosphatidylcholine',
                    'Secrete mucus to humidify inspired air',
                    'Differentiate into Clara cells after injury',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Type I pneumocytes are squamous cells that line most of the alveolar surface to permit gas diffusion.',
            ],
            [
                'topic' => 'Microbiology',
                'question' => 'A catheter-associated bloodstream infection grows coagulase-negative staphylococci. Which empiric therapy best covers this organism?',
                'choices' => [
                    'Vancomycin targeting methicillin-resistant staphylococci',
                    'Ampicillin-sulbactam covering beta-lactamase producers',
                    'Ceftriaxone providing broad gram-negative coverage',
                    'Azithromycin for intracellular atypical organisms',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Coagulase-negative staphylococci are usually methicillin resistant; vancomycin provides reliable empiric coverage.',
            ],
            [
                'topic' => 'Pharmacology',
                'question' => 'Which medication rapidly reverses unfractionated heparin in the setting of major bleeding?',
                'choices' => [
                    'Protamine sulfate forming an inactive complex with heparin',
                    'Vitamin K restoring hepatic clotting factor synthesis',
                    'Idarucizumab binding direct thrombin inhibitors',
                    'Andexanet alfa decoying factor Xa inhibitors',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Protamine sulfate is a positively charged peptide that neutralizes negatively charged heparin.',
            ],
            [
                'topic' => 'Cardiovascular System',
                'question' => 'Persistent ST-segment elevation with Q waves in anterior leads most likely indicates which condition?',
                'choices' => [
                    'Transmural infarction of the left anterior descending artery territory',
                    'Acute pericarditis with diffuse subepicardial injury',
                    'Left ventricular hypertrophy causing repolarization abnormalities',
                    'Electrolyte disturbance resulting in early repolarization',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Q waves with localized ST elevation reflect completed transmural infarction supplied by the LAD.',
            ],
            [
                'topic' => 'Respiratory System',
                'question' => 'A patient with severe asthma arrives with silent chest and pulsus paradoxus. What is the most appropriate immediate intervention?',
                'choices' => [
                    'Administer nebulized beta-2 agonist plus systemic corticosteroids while preparing for intubation',
                    'Obtain a chest radiograph prior to bronchodilator therapy',
                    'Begin long-acting muscarinic antagonist monotherapy',
                    'Start high-dose oral theophylline and observe response',
                ],
                'difficulty' => 'hard',
                'points' => 3,
                'explanation' => 'A near-fatal asthma exacerbation requires aggressive bronchodilation, systemic steroids, and airway preparation.',
            ],
            [
                'topic' => 'Gastrointestinal System',
                'question' => 'Which colonic polyp carries the highest risk for malignant transformation?',
                'choices' => [
                    'Villous adenoma larger than 1 cm',
                    'Hyperplastic polyp in the rectosigmoid colon',
                    'Inflammatory pseudopolyp in ulcerative colitis',
                    'Hamartomatous Peutz-Jeghers polyp',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Villous histology and size greater than 1 cm markedly increase malignancy risk.',
            ],
            [
                'topic' => 'Renal System',
                'question' => 'Microscopic hematuria with red blood cell casts is most specific for which diagnosis?',
                'choices' => [
                    'Glomerulonephritis causing nephritic syndrome',
                    'Nephrolithiasis with ureteral obstruction',
                    'Papillary necrosis from analgesic overuse',
                    'Bladder carcinoma involving the trigone',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'RBC casts signify glomerular inflammation or damage, distinguishing nephritic processes from lower tract sources.',
            ],
            [
                'topic' => 'Endocrine System',
                'question' => 'Which antithyroid therapy is preferred for a pregnant patient in her first trimester with Graves disease?',
                'choices' => [
                    'Propylthiouracil because it has lower teratogenic risk early in pregnancy',
                    'Methimazole due to once-daily dosing and better adherence',
                    'Radioactive iodine ablation to achieve definitive cure',
                    'Beta-blocker monotherapy to blunt adrenergic symptoms',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Propylthiouracil is favored in the first trimester as methimazole is associated with embryopathy.',
            ],
            [
                'topic' => 'Nervous System',
                'question' => 'Loss of dopaminergic neurons in the substantia nigra pars compacta leads to which neurotransmitter imbalance?',
                'choices' => [
                    'Decreased dopamine with relative excess acetylcholine in the striatum',
                    'Increased dopamine stimulating direct basal ganglia pathways',
                    'Reduced serotonin causing impaired mood regulation',
                    'Elevated norepinephrine within the locus coeruleus',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Parkinson disease features dopamine depletion resulting in cholinergic overactivity in the basal ganglia.',
            ],
            [
                'topic' => 'Musculoskeletal System',
                'question' => 'Which laboratory finding is most characteristic of rheumatoid arthritis?',
                'choices' => [
                    'Positive anti-citrullinated peptide antibodies with elevated ESR',
                    'High-titer anti-dsDNA antibodies with low complement',
                    'Elevated creatine kinase reflecting myocyte injury',
                    'Hyperuricemia with needle-shaped negatively birefringent crystals',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Anti-CCP antibodies are specific for rheumatoid arthritis and correlate with erosive disease.',
            ],
            [
                'topic' => 'Dermatology',
                'question' => 'An asymmetric pigmented lesion with irregular borders and color variegation should prompt concern for which diagnosis?',
                'choices' => [
                    'Malignant melanoma meeting ABCDE criteria',
                    'Seborrheic keratosis demonstrating the Leser-Trélat sign',
                    'Benign junctional nevus in a child',
                    'Cherry angioma commonly seen with aging',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'ABCDE warning signs point toward melanoma, necessitating excisional biopsy.',
            ],
            [
                'topic' => 'Oncology',
                'question' => 'Alpha-fetoprotein is most useful for surveillance of which malignancy?',
                'choices' => [
                    'Hepatocellular carcinoma in a cirrhotic patient',
                    'Medullary thyroid carcinoma associated with MEN2',
                    'Pancreatic adenocarcinoma of the head of pancreas',
                    'Colorectal carcinoma after right hemicolectomy',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Serum AFP levels correlate with tumor burden in hepatocellular carcinoma and yolk sac tumors.',
            ],
            [
                'topic' => 'Infectious Diseases',
                'question' => 'What is the recommended prophylaxis for a newborn whose mother has untreated HIV infection during labor?',
                'choices' => [
                    'Initiate zidovudine monotherapy immediately after birth',
                    'Administer ceftriaxone to prevent bacterial sepsis',
                    'Give palivizumab to reduce RSV complications',
                    'Start oseltamivir if the mother has influenza symptoms',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Intrapartum exposure requires neonatal zidovudine for six weeks to reduce vertical transmission.',
            ],
            [
                'topic' => 'Public Health',
                'question' => 'How is test sensitivity best defined?',
                'choices' => [
                    'The proportion of true positives correctly identified by the test',
                    'The probability that a positive result truly indicates disease',
                    'The likelihood ratio comparing positive to negative results',
                    'The prevalence of disease within the screened population',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Sensitivity measures how well a test detects disease among those who truly have it.',
            ],
            [
                'topic' => 'Evidence-Based Medicine',
                'question' => 'A hazard ratio of 0.70 (95% CI 0.60–0.90) for mortality in a trial implies what?',
                'choices' => [
                    'The intervention reduces the hazard of death by 30% compared with control',
                    'There is no statistically significant difference in outcomes',
                    'The control arm had better survival throughout follow-up',
                    'Absolute risk reduction of 30 percentage points was achieved',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'A hazard ratio below 1 with CI not crossing 1 means the intervention lowers the instantaneous risk by that proportion.',
            ],
            [
                'topic' => 'Medical Ethics',
                'question' => 'Respecting a patient’s informed refusal of chemotherapy despite high cure rates exemplifies which ethical principle?',
                'choices' => [
                    'Autonomy honoring the patient’s values and decisions',
                    'Beneficence prioritizing the patient’s best interest',
                    'Nonmaleficence avoiding harm through overtreatment',
                    'Justice ensuring fair allocation of resources',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Autonomy obligates clinicians to respect competent patients’ choices even when they differ from medical recommendations.',
            ],
            [
                'topic' => 'Clinical Skills',
                'question' => 'Detection of pulsus paradoxus greater than 12 mm Hg most strongly suggests which diagnosis in the appropriate clinical context?',
                'choices' => [
                    'Cardiac tamponade impairing diastolic filling',
                    'Aortic regurgitation with wide pulse pressure',
                    'Hypertrophic obstructive cardiomyopathy',
                    'Peripheral arterial disease with claudication',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Marked pulsus paradoxus is classic for tamponade, severe asthma, or constrictive pericarditis.',
            ],
            [
                'topic' => 'Emergency Medicine',
                'question' => 'Which intervention should be performed immediately when a patient develops a tension pneumothorax after trauma?',
                'choices' => [
                    'Needle decompression in the second intercostal space midclavicular line',
                    'Chest radiograph to confirm lung collapse before treatment',
                    'Endotracheal intubation prior to any thoracic intervention',
                    'Placement of a chest tube without prior decompression',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Tension physiology mandates emergent needle decompression before definitive tube thoracostomy.',
            ],
            [
                'topic' => 'Pediatrics',
                'question' => 'At what age should the first dose of the MMR vaccine typically be administered?',
                'choices' => [
                    'Between 12 and 15 months of age',
                    'At birth during the initial newborn visit',
                    'At 2 months along with the primary series',
                    'Delayed until the child enters elementary school',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'MMR is scheduled at 12–15 months with a booster at 4–6 years.',
            ],
            [
                'topic' => 'Obstetrics & Gynecology',
                'question' => 'A painless third-trimester bleed with a low-lying placenta on ultrasound suggests placenta previa. What is the recommended management?',
                'choices' => [
                    'Plan a scheduled cesarean delivery at 36–37 weeks if bleeding stabilizes',
                    'Attempt induction of labor with oxytocin at term',
                    'Perform immediate classical cesarean at diagnosis regardless of gestation',
                    'Offer vaginal delivery if fetal head is engaged',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Placenta previa warrants pelvic rest and planned cesarean once fetal maturity is reached.',
            ],
            [
                'topic' => 'Surgery',
                'question' => 'Using the Parkland formula, how much lactated Ringer’s solution should be given in the first 24 hours to a 70-kg adult with 30% TBSA burns?',
                'choices' => [
                    '8.4 liters with half administered in the first 8 hours',
                    '2.1 liters delivered evenly over 24 hours',
                    '4.2 liters front-loaded over 8 hours',
                    '10.5 liters infused continuously over 24 hours',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Parkland formula: 4 mL × weight × %TBSA = 8,400 mL; deliver half in first 8 hours.',
            ],
            [
                'topic' => 'Internal Medicine',
                'question' => 'Bilateral hilar adenopathy with erythema nodosum in a young woman most strongly indicates which diagnosis?',
                'choices' => [
                    'Sarcoidosis causing noncaseating granulomas',
                    'Primary tuberculosis infection',
                    'Coccidioidomycosis acquired in the desert Southwest',
                    'Pulmonary lymphoma with mediastinal involvement',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Löfgren syndrome in sarcoidosis features hilar adenopathy, erythema nodosum, and arthralgias.',
            ],
            [
                'topic' => 'Radiology',
                'question' => 'What is the best initial imaging study for suspected acute subarachnoid hemorrhage?',
                'choices' => [
                    'Non-contrast head CT performed emergently',
                    'MRI brain with gadolinium contrast',
                    'CT angiography of the head and neck first',
                    'Lumbar puncture before any imaging',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'A non-contrast CT rapidly identifies acute blood and guides further management.',
            ],
            [
                'topic' => 'Anesthesiology',
                'question' => 'Rapid-sequence induction for emergent intubation includes which essential component?',
                'choices' => [
                    'Application of cricoid pressure with immediate paralysis and no bag-mask ventilation',
                    'Slow escalation of inhaled anesthetics before neuromuscular blockade',
                    'Routine use of spinal anesthesia to blunt reflexes',
                    'Administration of naloxone before induction medications',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Rapid-sequence induction minimizes aspiration risk using cricoid pressure and prompt neuromuscular blockade.',
            ],
            [
                'topic' => 'Family Medicine',
                'question' => 'Average-risk adults should begin colorectal cancer screening at what age?',
                'choices' => [
                    'Age 45 with colonoscopy or equivalent screening test',
                    'Age 30 if there is any family history of cancer',
                    'Age 55 provided there are no symptoms',
                    'Screening is unnecessary if annual fecal occult blood tests are normal',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Updated guidelines recommend initiating screening at age 45 for average-risk individuals.',
            ],
            [
                'topic' => 'Ophthalmology',
                'question' => 'Acute angle-closure glaucoma should first be treated with which medication?',
                'choices' => [
                    'Topical timolol combined with systemic acetazolamide',
                    'Long-term prostaglandin analogs only',
                    'Topical corticosteroids to reduce inflammation',
                    'Observation until corneal edema resolves spontaneously',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Immediate pressure reduction using beta-blockers plus carbonic anhydrase inhibitors is critical.',
            ],
            [
                'topic' => 'Otolaryngology',
                'question' => 'A diabetic swimmer presents with severe otalgia and granulation tissue in the ear canal. The most likely pathogen is:',
                'choices' => [
                    'Pseudomonas aeruginosa causing malignant otitis externa',
                    'Streptococcus pyogenes producing beta-hemolysis',
                    'Candida albicans leading to otomycosis',
                    'Human herpesvirus 3 producing Ramsay Hunt syndrome',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Malignant otitis externa in diabetics is usually due to Pseudomonas and requires antipseudomonal therapy.',
            ],
            [
                'topic' => 'Urology',
                'question' => 'An elevated PSA after prostatectomy is best interpreted as:',
                'choices' => [
                    'Biochemical recurrence requiring further staging',
                    'Residual benign hyperplasia of the transition zone',
                    'Expected PSA bounce from radiation therapy',
                    'Laboratory error that can be ignored',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Any detectable PSA after prostate removal suggests recurrent disease and warrants evaluation.',
            ],
            [
                'topic' => 'Psychiatry',
                'question' => 'Which medication is first-line for long-term management of obsessive-compulsive disorder?',
                'choices' => [
                    'High-dose selective serotonin reuptake inhibitor therapy',
                    'Short-acting benzodiazepines used as monotherapy',
                    'Low-dose first-generation antipsychotics alone',
                    'Tricyclic antidepressants as initial therapy for all patients',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'SSRIs at higher doses combined with CBT are first-line for OCD.',
            ],
            [
                'topic' => 'Immunology',
                'question' => 'Recurrent swelling of the face and airway without urticaria after minor trauma is most consistent with deficiency of which protein?',
                'choices' => [
                    'C1 esterase inhibitor leading to hereditary angioedema',
                    'Factor V causing impaired coagulation cascade',
                    'Selective IgA resulting in sinopulmonary infections',
                    'Properdin involved in the alternative complement pathway',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'C1 inhibitor deficiency permits unchecked bradykinin production, producing hereditary angioedema.',
            ],
            [
                'topic' => 'Anatomy',
                'question' => 'Compression within the carpal tunnel most directly injures which structure?',
                'choices' => [
                    'Median nerve beneath the flexor retinaculum',
                    'Ulnar nerve as it traverses Guyon canal',
                    'Radial artery within the anatomical snuffbox',
                    'Flexor carpi radialis tendon lying superficial to the tunnel',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'The carpal tunnel contains the median nerve and flexor tendons, so neuropathy produces paresthesias.',
            ],
            [
                'topic' => 'Physiology',
                'question' => 'The plateau (phase 2) of the ventricular action potential is primarily due to which ionic current?',
                'choices' => [
                    'Slow influx of calcium through L-type channels',
                    'Rapid efflux of potassium through delayed rectifier channels',
                    'Funny current sodium influx during pacemaker depolarization',
                    'Chloride influx activated by GABA receptors',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Phase 2 is sustained by Ca2+ entry via L-type channels balanced by K+ efflux.',
            ],
            [
                'topic' => 'Biochemistry',
                'question' => 'Which enzyme catalyzes the rate-limiting step of glycolysis and is inhibited by ATP and citrate?',
                'choices' => [
                    'Phosphofructokinase-1',
                    'Glucokinase',
                    'Pyruvate kinase',
                    'Enolase',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'PFK-1 commits glucose to glycolysis and responds to the cell’s energy status.',
            ],
            [
                'topic' => 'Histology',
                'question' => 'Podocytes within the renal corpuscle perform which function?',
                'choices' => [
                    'Form the visceral layer of Bowman capsule with filtration slits',
                    'Line the parietal layer producing paracrine factors',
                    'Reabsorb filtered glucose in the proximal tubule',
                    'Secrete renin into the afferent arteriole',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Podocyte foot processes interdigitate to create the slit diaphragm of the filtration barrier.',
            ],
            [
                'topic' => 'Cardiovascular System',
                'question' => 'Which biomarker correlates with ventricular wall stress and is elevated in decompensated heart failure?',
                'choices' => [
                    'B-type natriuretic peptide (BNP)',
                    'Cardiac troponin I',
                    'Creatine kinase-MB fraction',
                    'D-dimer fragments',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'BNP is released from ventricles in response to stretch and guides heart failure therapy.',
            ],
            [
                'topic' => 'Respiratory System',
                'question' => 'Which arterial blood gas pattern is most characteristic of an acute pulmonary embolism?',
                'choices' => [
                    'Respiratory alkalosis with low PaCO₂ due to hyperventilation',
                    'Respiratory acidosis with elevated PaCO₂',
                    'Normal PaO₂ and PaCO₂ because perfusion is unaffected',
                    'Metabolic acidosis with elevated anion gap from lactate',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'PE stimulates tachypnea, producing hypocapnia and mild respiratory alkalosis.',
            ],
            [
                'topic' => 'Gastrointestinal System',
                'question' => 'Which serologic assay is most specific for celiac disease?',
                'choices' => [
                    'IgA anti–tissue transglutaminase antibodies',
                    'IgM anti-mitochondrial antibodies',
                    'Anti-centromere antibodies',
                    'Anti-topoisomerase I antibodies',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'IgA anti-tTG antibodies are the preferred screening and monitoring test for celiac disease.',
            ],
            [
                'topic' => 'Renal System',
                'question' => 'Angiotensin-converting enzyme inhibitors provide renal protection in diabetes primarily by:',
                'choices' => [
                    'Dilating the efferent arteriole to lower intraglomerular pressure',
                    'Constraining the afferent arteriole to reduce filtration',
                    'Stimulating aldosterone to increase distal sodium reabsorption',
                    'Inducing mesangial cell proliferation to support the basement membrane',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'ACE inhibitors preferentially dilate efferent arterioles, reducing glomerular hypertension and proteinuria.',
            ],
            [
                'topic' => 'Endocrine System',
                'question' => 'Secondary hyperparathyroidism from chronic kidney disease typically demonstrates which laboratory triad?',
                'choices' => [
                    'Hypocalcemia, hyperphosphatemia, elevated PTH',
                    'Hypercalcemia, hypophosphatemia, suppressed PTH',
                    'Normocalcemia, hyperphosphatemia, low PTH',
                    'Hypercalcemia, hyperphosphatemia, low PTH',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Phosphate retention and low vitamin D cause hypocalcemia, stimulating secondary PTH elevation.',
            ],
            [
                'topic' => 'Nervous System',
                'question' => 'What is the preferred initial imaging modality when evaluating an acute ischemic stroke for thrombolysis eligibility?',
                'choices' => [
                    'Non-contrast CT of the head',
                    'MRI brain with gadolinium contrast',
                    'Carotid duplex ultrasonography',
                    'Positron emission tomography scan',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'A non-contrast CT rapidly excludes intracranial hemorrhage before administering thrombolytics.',
            ],
            [
                'topic' => 'Musculoskeletal System',
                'question' => 'Which therapy provides rapid relief for an acute gout flare in a patient with preserved renal function?',
                'choices' => [
                    'High-dose nonsteroidal anti-inflammatory drugs such as indomethacin',
                    'Initiate allopurinol immediately at a high dose',
                    'Start probenecid during the painful episode',
                    'Use colchicine only as long-term prophylaxis',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'NSAIDs are first-line for acute gout, whereas urate-lowering drugs are not started during flares.',
            ],
            [
                'topic' => 'Dermatology',
                'question' => 'Stevens-Johnson syndrome is most commonly precipitated by which exposure?',
                'choices' => [
                    'Sulfonamide antibiotics leading to severe mucocutaneous reactions',
                    'Chronic ultraviolet light in outdoor workers',
                    'Human papillomavirus infection of keratinocytes',
                    'Localized Staphylococcus aureus colonization',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'High-risk medications such as sulfonamides, allopurinol, and some anticonvulsants trigger SJS/TEN.',
            ],
            [
                'topic' => 'Oncology',
                'question' => 'BRCA1 and BRCA2 gene products normally participate in which cellular process?',
                'choices' => [
                    'Homologous recombination repair of double-strand DNA breaks',
                    'Activation of epidermal growth factor receptors',
                    'Promotion of angiogenesis through VEGF production',
                    'Regulation of telomerase extension',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Loss of BRCA-mediated DNA repair increases genomic instability and cancer risk.',
            ],
            [
                'topic' => 'Infectious Diseases',
                'question' => 'Which regimen is recommended for latent tuberculosis infection in an immunocompetent adult?',
                'choices' => [
                    'Daily isoniazid for nine months with pyridoxine supplementation',
                    'Empiric four-drug therapy for two months only',
                    'Azithromycin once weekly for three months',
                    'Observation without treatment if the chest radiograph is normal',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Latent TB is treated with prolonged isoniazid or rifamycin-based therapy to prevent reactivation.',
            ],
            [
                'topic' => 'Public Health',
                'question' => 'How is number needed to treat (NNT) calculated?',
                'choices' => [
                    'It is the inverse of the absolute risk reduction',
                    'It equals the inverse of the relative risk reduction',
                    'It matches the reciprocal of the hazard ratio',
                    'It equals sensitivity divided by specificity',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'NNT = 1 / |control event rate − experimental event rate|.',
            ],
            [
                'topic' => 'Evidence-Based Medicine',
                'question' => 'Analyzing trial participants in the groups to which they were randomized, regardless of adherence, reflects which approach?',
                'choices' => [
                    'Intention-to-treat analysis preserving randomization',
                    'Per-protocol analysis focusing on adherent subjects',
                    'Noninferiority design comparing margins',
                    'Cross-over methodology',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Intention-to-treat protects against attrition bias by keeping participants in their original groups.',
            ],
            [
                'topic' => 'Medical Ethics',
                'question' => 'Breaking patient confidentiality is ethically acceptable under which circumstance?',
                'choices' => [
                    'When a patient makes a credible threat to harm an identifiable person',
                    'When family members request updates without consent',
                    'When the physician disagrees with the patient’s lifestyle choices',
                    'When the diagnosis carries social stigma',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Duty to warn or protect may override confidentiality when imminent harm to others is likely.',
            ],
            [
                'topic' => 'Clinical Skills',
                'question' => 'An ankle-brachial index of 0.60 indicates which degree of peripheral arterial disease?',
                'choices' => [
                    'Moderate disease warranting vascular referral',
                    'Normal perfusion without hemodynamic compromise',
                    'Mild disease that requires no intervention',
                    'Noncompressible calcified vessels producing false readings',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'ABI 0.40–0.69 corresponds to moderate PAD associated with exertional claudication.',
            ],
            [
                'topic' => 'Emergency Medicine',
                'question' => 'Massive transfusion protocols for hemorrhagic shock target which ratio of plasma:platelets:packed red cells?',
                'choices' => [
                    '1:1:1 to approximate whole blood',
                    '1:2:4 emphasizing red cells',
                    '1:4:1 prioritizing platelets',
                    '0:1:1 eliminating plasma',
                ],
                'difficulty' => 'hard',
                'points' => 3,
                'explanation' => 'Balanced resuscitation with a 1:1:1 ratio improves survival in severe trauma.',
            ],
            [
                'topic' => 'Pediatrics',
                'question' => 'What therapy reduces the risk of coronary aneurysms in Kawasaki disease?',
                'choices' => [
                    'High-dose intravenous immunoglobulin plus aspirin',
                    'Systemic corticosteroids alone',
                    'Broad-spectrum antibiotics targeting streptococci',
                    'Observation because the illness is always self-limited',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Timely IVIG and aspirin are essential to reduce coronary artery complications.',
            ],
            [
                'topic' => 'Obstetrics & Gynecology',
                'question' => 'A pregnant patient with tonic-clonic seizures and severe hypertension most likely has eclampsia. What is the immediate management priority?',
                'choices' => [
                    'Administer intravenous magnesium sulfate and prepare for delivery',
                    'Start diazepam infusion for chronic seizure suppression',
                    'Delay any intervention until fetal lung maturity testing is complete',
                    'Initiate tocolytics to halt uterine contractions',
                ],
                'difficulty' => 'hard',
                'points' => 3,
                'explanation' => 'Eclampsia requires magnesium sulfate to prevent recurrent seizures and expedited delivery.',
            ],
            [
                'topic' => 'Surgery',
                'question' => 'Which imaging modality is first-line for suspected acute cholecystitis in the emergency department?',
                'choices' => [
                    'Right upper quadrant ultrasound showing gallstones and wall thickening',
                    'Plain abdominal radiography',
                    'CT abdomen without contrast as the initial study',
                    'Barium upper GI series',
                ],
                'difficulty' => 'easy',
                'points' => 1,
                'explanation' => 'Ultrasound reveals gallstones, pericholecystic fluid, and sonographic Murphy sign in acute cholecystitis.',
            ],
            [
                'topic' => 'Internal Medicine',
                'question' => 'Which sequence best describes initial management of diabetic ketoacidosis?',
                'choices' => [
                    'Aggressive isotonic fluid resuscitation followed by insulin infusion',
                    'Immediate bicarbonate bolus before fluids',
                    'High-dose subcutaneous insulin without IV access',
                    'Fluid restriction to avoid cerebral edema',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Volume repletion with normal saline precedes insulin to restore perfusion and potassium balance.',
            ],
            [
                'topic' => 'Radiology',
                'question' => 'A hemodynamically stable patient with high suspicion for pulmonary embolism should undergo which diagnostic test?',
                'choices' => [
                    'CT pulmonary angiography',
                    'Ventilation-perfusion scan in all cases',
                    'Lower extremity Doppler ultrasound only',
                    'Chest radiograph sufficient for diagnosis',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'CTPA directly visualizes emboli and is first-line in most stable patients without contraindications.',
            ],
            [
                'topic' => 'Anesthesiology',
                'question' => 'What is the antidote for malignant hyperthermia triggered by volatile anesthetics or succinylcholine?',
                'choices' => [
                    'Dantrolene sodium',
                    'Sugammadex',
                    'Physostigmine',
                    'Flumazenil',
                ],
                'difficulty' => 'medium',
                'points' => 2,
                'explanation' => 'Dantrolene blocks ryanodine receptors, halting calcium release from the sarcoplasmic reticulum.',
            ],
        ];
    }
}
